spring.application.name=TerraForm API

spring.datasource.url=jdbc:h2:mem:terraform
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.error.include-message=always

terraform.simulation.tick-ms=15000
terraform.soap.chemical-synthesis-url=http://localhost:8080/ws
terraform.soap.client-user=operator
terraform.soap.client-password=terraform-operator

terraform.security.admin-user=admin
terraform.security.admin-password=terraform-admin
terraform.security.operator-user=operator
terraform.security.operator-password=terraform-operator
terraform.security.viewer-user=viewer
terraform.security.viewer-password=terraform-viewer

springdoc.swagger-ui.doc-expansion=list
springdoc.swagger-ui.docExpansion=list
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
